---
# Tasks to setup network

- name: Fetch node files
  git:
    repo: "https://{{ network_launch_repository }}.git"
    dest: "{{ ansible_env.HOME }}/launch"
    recursive: false
    version: "{{ network_launch_branch }}"

- name: Setup node directory
  command: cp -rf {{ ansible_env.HOME }}/launch/{{ network_version }}/{{ node_type }} {{ ansible_env.HOME }}/node

- name: Setup Heidmall
  command: "chdir={{ ansible_env.HOME }}/node/heimdall {{ item }}"
  with_items:
    - bash setup.sh
  tags:
    - heimdall

- name: Setup Bor
  command: "chdir={{ ansible_env.HOME }}/node/bor {{ item }}"
  with_items:
    - bash setup.sh
  tags:
    - bor

- name: Generate service files
  command: "chdir={{ ansible_env.HOME }}/launch/{{ network_version }} {{ item }}"
  with_items:
    - bash service.sh
