---
# vars file for roles/setup-network

# repository
network_launch_repository: github.com/shibaswaparmy/launch
# branch
network_launch_branch: alpha_v3   #needs change
# version
network_version: alpha_v3
# node type
# options: sentry/sentry, sentry/validator, without-sentry
node_type: sentry/sentry
