---
- name: Create Ec2 instances
  hosts: localhost
  gather_facts: False
  tasks:

  - name: Create EC2 Block
    block: 

      - name: Launch ec2 instances
        tags: create_ec2
        ec2:
          region: "{{ aws_region }}"
          key_name: "{{ aws_keypair }}"
          group_id: "{{ aws_sg_id }}"
          instance_type: "{{ aws_instance_type }}"
          image: "{{ aws_ami_id }}"
          # instance_profile_name: "{{ iam_profile_name }}"
          wait: yes
          wait_timeout: 500
          count:  "{{ aws_instance_count_sentry | int }}"
          instance_tags:
            Name: "{{ aws_instance_tag_sentry }}"
            os: ubuntu
          monitoring: no
          vpc_subnet_id: "{{ aws_subnet_id }}"
          assign_public_ip: yes
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          # user_data: "{{ lookup('file', '../user_data.sh') }}"
          volumes: 
            - device_name: /dev/sda1
              volume_size: "{{ aws_ebs_size | int }}"
              volume_type: "{{ aws_ebs_type }}"
              delete_on_termination: true
        register: ec2
        delegate_to: localhost
        when: aws_instance_count_sentry | int  >= 1

      - name: Wait for SSH to come up
        local_action:
          module: wait_for
          host: "{{ item.public_ip }}"
          port: 22
          delay: 10
          timeout: 120
        loop: "{{ ec2.instances }}"
        when: aws_instance_count_sentry | int  >= 1

      - name: Display Public IP
        debug:
          msg: "{{ item.public_ip }}"
        with_items:
          - "{{ ec2.instances }}"
        loop_control:
          label:  "Pub_IP"
        when: aws_instance_count_sentry | int  >= 1

    # By specifying never on the tag of this block, 
    # I let this block to run only when explicitely being called
    tags: ['never', 'ec2-create']
  
